name: Check Containers

on:
  pull_request:
    paths:
      - ".github/workflows/check-containers.ya?ml"
      - "**.Dockerfile"
      - "**/Dockerfile"
  push:
    paths:
      - ".github/workflows/check-containers.ya?ml"
      - "**.Dockerfile"
      - "**/Dockerfile"
  repository_dispatch:
  schedule:
    - cron: "0 7 * * MON"
  workflow_dispatch:

jobs:
  run:
    name: Build & Push (${{ matrix.image.path }})
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: name/app:latest
      REGISTRY: 127.0.0.1:5000

    strategy:
      fail-fast: false
      matrix:
        image:
          - path: ".github/workflows/assets/linux.Dockerfile"
          
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

        # Registry im Runner starten
      - name: Start local registry
        run: docker run -d -p 5000:5000 --name registry registry:2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: image=moby/buildkit:latest,network=host

      - name: Build and push to local registry
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.image.path }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          platforms: linux/amd64,linux/arm64
